Query and update animals table
sainingo/vet_clinic_database pull request #2
Opened 2022-06-07 21:17 UTC by sainingo

1. Added a column species of type string to the animal's table. Modified your schema.sql file.
2. Inserted the data.
3. updated the animal's table by setting the species column to unspecified.
4. Inside a transaction:

- Deleted all animals born after Jan 1st, 2022.
- Created a savepoint for the transaction.
- Updated all animals' weight to be their weight multiplied by -1.
- Rollback to the savepoint
- Updated all animals' weights that are negative to be their weight multiplied by -1.
- Committed transaction

2022-06-07 22:02 UTC, sja-thedude requested changes
## Required Changes ♻️

Hi @sainingo, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![768070f3-bc9a-4aba-b8bc-25793e00ea1e_text](https://user-images.githubusercontent.com/70269507/159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff.gif)

## Highlights
✔️ Good Job So far
✔️ Correct Gitflow
✔️ Good PR Description and Title

## Required 
- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-07 22:02 UTC, sja-thedude commented on schema.sql
> +ALTER TABLE animals ADD species character
- [ ] Kindly add a string type for the column species. For this, you have to add varchar with a limit like: 
`ALTER TABLE animals ADD species varchar(255);`

2022-06-07 22:02 UTC, sja-thedude commented on data.sql
> +INSERT INTO animals (id,name,date_of_birth,escape_attempts,neutered,weight_kg,species) VALUES (8, 'Angemon', '2005-06-12', 1, 'true', 45.0, '' );
- [ ] Kindly add correct weight for animals Charmander, Plantmon, Squirtle, and Angemon. Make sure to add (-) before their weight like `-11.0 for Charmander`. As per the project requirements, all these animals' weights are less than 0 and are in minus.

2022-06-07 22:02 UTC, sja-thedude commented on queries.sql
> +SELECT COUNT(*) FROM animals WHERE escape_attempts = 0;
- [ ] Kindly make sure to answer all the questions given. You have not answered:
- What is the average weight of animals?
- Who escapes the most, neutered or not neutered animals?
- What is the minimum and maximum weight of each type of animal?
- What is the average number of escape attempts per animal type of those born between 1990 and 2000?

2022-06-07 22:02 UTC, sja-thedude commented on queries.sql
> +-- SAVE POINT
- [ ] Instead of commenting save point you should write the query for save point. 
Example: SAVEPOINT SP1;

2022-06-07 22:02 UTC, sja-thedude commented on queries.sql
> +UPDATE animals SET species = 'pokemon' WHERE species = NULL;
- [ ] Kindly add `BEGIN;`  before the update query to begin your transaction.
- [ ] Kindly add `Select` query for species to verify the change made after update query.
- [ ] Make sure to `COMMIT`; and then again verify the change persists after COMMIT with the select query as per the requirements.

2022-06-07 22:02 UTC, sja-thedude commented on queries.sql
> +ROLLBACK BeforeDelete;
- [ ] As per the requirements you have to do-:
Inside a transaction delete all records in the animal's table, then roll back the transaction.
After the rollback verify if all records in the animal's table still exist. 
_For this, you have to first begin the transaction then use delete query then select query to check all records then roll back, and finally, you have to again check all the records with select query._

2022-06-07 22:02 UTC, sja-thedude commented on queries.sql
> +
- [ ] You have not added the below requirements for this project:-
Inside a transaction update the animal's table by setting the species column to unspecified. Verify that change was made. Then roll back the change and verify that species columns went back to the state before the transaction.

2022-06-08 07:17 UTC, emmanuellekamwa approved these changes
**STATUS: APPROVED 🍾✔🎉**
Hello @sainingo 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-08 09:22 UTC, merged